apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress-controller
spec:
  values:
    ingressClassResource:
      default: true
      name: nginx-internal
    electionID: internal-ingress-controller-leader
