apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress-controller
spec:
  values:
    ingressClassResource:
      default: true
      name: nginx-internal
      controllerClass: "k8s.io/ingress-nginx-internal"
    electionID: internal-ingress-controller-leader
    tcp:
      "22": "gitlab/gitlab-gitlab-shell:22"
