apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: route53
spec:
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: "6.27.0"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  # Default values
  # https://artifacthub.io/packages/helm/bitnami/external-dns?modal=values
  values:
#    dryRun: true
    txtPrefix: edns-
    aws:
      credentials:
        secretName: route53-credentials
      zoneType: public
