apiVersion: v1
kind: Secret
metadata:
  name: route53-credentials
  namespace: external-dns
type: Opaque
stringData:
  credentials: |
    [default]
    aws_access_key_id = 
    aws_secret_access_key = 
