---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: observability
spec:
  version: 7.16.2
  nodeSets:
    - name: data
      count: 3
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
      config:
        node.store.allow_mmap: false
        xpack.security.authc:
          anonymous:
            username: anonymous_user
            roles: kibana_admin, viewer, superuser
            authz_exception: true
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: observability
spec:
  version: 7.16.2
  count: 1
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  elasticsearchRef:
    name: observability
  config:
    xpack.security.enabled: false
    server.publicBaseUrl: "https://observability.${environment}.${domain}"
  podTemplate:
    spec:
      containers:
        - name: kibana
          readinessProbe:
            httpGet:
              path: "/status"
              port: 5601
              scheme: HTTP
