apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress-controller
spec:
  values:
    ingressClassResource:
      name: nginx-external
    electionID: external-ingress-controller-leader
