apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nginx
namePrefix: external-
resources:
  - ../ingress-base
  - github-secret.yaml
  - oauth-ingress.yaml
  - oauth2-proxy.yaml
patchesStrategicMerge:
  - controller-values.yaml
