apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-example
spec:
  # Secret names are always required.
  secretName: letsencrypt-example-staging

  dnsNames:
    - letsencrypt-example-staging.${environment}.${domain}

  issuerRef:
    name: letsencrypt-route53-staging
    kind: ClusterIssuer
