apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sealed-secrets
  - sources
  - nginx
  - longhorn
  - coredns.yaml
  - cert-manager
  - metallb
  - monitoring
  - eck
#  - observability
