apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress-controller
spec:
  values:
    ingressClassResource:
      default: false
      name: nginx-external-noauth
      controllerClass: "k8s.io/ingress-external-noauth"
    electionID: external-noauth-ingress-controller-leader
    publishService:
      pathOverride: "nginx/k9s-external"
    tcp:
      "22": "gitlab/gitlab-gitlab-shell:22"
