apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ceph-csi-rbd
spec:
  chart:
    spec:
      chart: ceph-csi-rbd
      sourceRef:
        kind: HelmRepository
        name: ceph-csi
      version: "3.8.0"
  interval: 1h0m0s
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    secret:
      create: true
      userID: admin
      userKey: "AQC2ZihgJbzABBAA3RDoADmmVW49CYNB+QNhwg=="
    storageClass:
      create: false
    csiConfig:
      - clusterID: "c83cff86-6529-46c7-974f-efb4c175a36b"
        monitors:
        - "192.168.86.242:6789"
        - "192.168.86.243:6789"
        - "192.168.86.244:6789"
    kubeletDir: "/var/snap/microk8s/common/var/lib/kubelet"
