apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ceph-csi-rbd
spec:
  chart:
    spec:
      chart: ceph-csi-rbd
      sourceRef:
        kind: HelmRepository
        name: ceph-csi
      version: "3.14.2"
  interval: 1h0m0s
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    secret:
      create: true
      userID: admin
      userKey: "AQAmeP9mUfQaMhAAkJws2wl2TzC8UcyB4W08Gg=="
    storageClass:
      create: false
    csiConfig:
      - clusterID: "2d70006f-5a98-452a-a07d-8cea4228248f"
        monitors:
        - "192.168.86.241:6789"
        - "192.168.86.242:6789"
        - "192.168.86.243:6789"
        - "192.168.86.244:6789"
    kubeletDir: "/var/snap/microk8s/common/var/lib/kubelet"
