apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: rbd
driver: rbd.csi.ceph.com
parameters:
  clusterID: 2d70006f-5a98-452a-a07d-8cea4228248f
  csi.storage.k8s.io/snapshotter-secret-name: csi-rbd-secret
  csi.storage.k8s.io/snapshotter-secret-namespace: rbd-csi
deletionPolicy: Delete
