apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rbd
provisioner: rbd.csi.ceph.com
parameters:
  clusterID: c83cff86-6529-46c7-974f-efb4c175a36b
  csi.storage.k8s.io/controller-expand-secret-name: csi-rbd-secret
  csi.storage.k8s.io/controller-expand-secret-namespace: rbd-csi
  csi.storage.k8s.io/fstype: ext4
  csi.storage.k8s.io/node-stage-secret-name: csi-rbd-secret
  csi.storage.k8s.io/node-stage-secret-namespace: rbd-csi
  csi.storage.k8s.io/provisioner-secret-name: csi-rbd-secret
  csi.storage.k8s.io/provisioner-secret-namespace: rbd-csi
  imageFeatures: layering
  pool: ${environment}-mk8s-rbd
  thickProvision: "false"
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
