apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
spec:
  interval: 10m
  chart:
    spec:
      version: 44.3.1
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      interval: 1m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    alertmanager:
      enabled: true
    grafana:
      defaultDashboardsTimezone: browser
      ingress:
        enabled: true
        ingressClassName: nginx-internal
        annotations:
          kubernetes.io/tls-acme: "true"
        hosts:
          - grafana.${environment}.${domain}
        tls:
          - secretName: grafana-monitoring-tls
            hosts:
            - grafana.${environment}.${domain}
      sidecar:
        dashboards:
          searchNamespace: ALL
    prometheus:
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false
        storageSpec:
          volumeClaimTemplate:
            spec:
              resources:
                requests:
                  storage: 10Gi
