apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: elastic-system
resources:
  - https://download.elastic.co/downloads/eck/2.8.0/crds.yaml
  - https://download.elastic.co/downloads/eck/2.8.0/operator.yaml
commonAnnotations:
  kustomize.toolkit.fluxcd.io/substitute: disabled
