apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: logs
spec:
  version: 7.17.15
  count: 1
  elasticsearchRef:
    name: logs
  kibanaRef:
    name: logs
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  config:
    xpack.security.enabled: false
    server.publicBaseUrl: "https://apm.es.${environment}.${domain}"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: es-apm-ingress
  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-connect-timeout:  "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
#    nginx.ingress.kubernetes.io/auth-url: "https://auth.${environment}.${domain}/oauth2/auth"
#    nginx.ingress.kubernetes.io/auth-signin: "https://auth.${environment}.${domain}/oauth2/start?rd=$escaped_request_uri"
spec:
  ingressClassName: nginx-internal
  tls:
    - hosts:
        - apm.es.${environment}.${domain}
      secretName: es-apm-tls
  rules:
    - host: apm.es.${environment}.${domain}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: logs-apm-http
                port:
                  number: 8200
