apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: logs
spec:
  version: 7.17.15
  nodeSets:
    - name: data
      count: 3
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 500Gi
            storageClassName: longhorn
      config:
        xpack.security.authc:
          anonymous:
            username: anonymous_user
            roles: kibana_admin, viewer, superuser
            authz_exception: true
      podTemplate:
       spec:
         containers:
         - name: elasticsearch
           env:
           - name: ES_JAVA_OPTS
             value: -Xms3g -Xmx3g
           resources:
             requests:
               memory: 4Gi
             limits:
               memory: 4Gi
