apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: logs
spec:
  version: 7.17.15
  nodeSets:
    - name: data
      count: 3
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 500Gi
            storageClassName: longhorn
      config:
        xpack.security.authc:
          anonymous:
            username: anonymous_user
            roles: kibana_admin, viewer, superuser
            authz_exception: true
