apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-route53
spec:
  acme:
    email: ${owner_email}
    preferredChain: "ISRG Root X1"

    solvers:
      - selector:
          dnsZones: [ "${environment}.${domain}" ]
        dns01:
          route53:
            region: us-west-2
            accessKeyID: ${route53_accessKeyID}
            hostedZoneID: ${route53_hostedZoneID}
            secretAccessKeySecretRef:
              name: route53-credentials
              key: AWS_SECRET_ACCESS_KEY
      - selector:
          dnsZones: [ "${environment}.${domain}" ]
        http01:
          ingress:
            class: nginx-external-noauth
