    # Docs https://github.com/itzg/docker-minecraft-server/blob/master/README.md

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: "minecraft"
spec:
  # https://github.com/itzg/minecraft-server-charts/blob/master/charts/minecraft/values.yaml
  values:
    image:
      tag: java8-multiarch
    minecraftServer:
      motd: "Welcome to RandyCraft Server"
      type: "FORGE"
      forgeVersion: "36.2.39"
      version: "1.16.5"
      gameMode: survival
      difficulty: normal
      levelType: biomesoplenty
      #removeOldMods: true
      memory: 4G

    extraEnv:
      PACKWIZ_URL: https://k9s.pages.gitlab.app.k9s.io/minecraft/randycraft-modpack/pack.toml
