apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: "minecraft"
spec:
  chart:
    spec:
      chart: minecraft
      sourceRef:
        kind: HelmRepository
        name: itzg
        namespace: minecraft
      version: "4.7.4"
  interval: 1m
  values:
    minecraftServer:
      eula: "TRUE"
      ops: "2535412894030195,2535468526729235"
      serviceType: LoadBalancer

    persistence:
      dataDir:
        enabled: true
        Size: 10Gi
