apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: "bedrock"
spec:
  chart:
    spec:
      chart: minecraft-bedrock
      sourceRef:
        kind: HelmRepository
        name: itzg
        namespace: minecraft
      version: "1.2.1"
  interval: 1m
  values:
    # ref: https://hub.docker.com/r/itzg/minecraft-server/
    image: itzg/minecraft-bedrock-server
    imageTag: latest

    strategyType: Recreate

    minecraftServer:
      eula: "TRUE"
      # One of: LATEST, SNAPSHOT, or a specific version (ie: "1.7.9").
      version: "LATEST"
      # One of: peaceful, easy, normal, and hard
      difficulty: easy
      whitelist:
      whitelistUsers:
      ops: "2535412894030195,2535468526729235"
      members:
      visitors:
      maxPlayers: 10
      tickDistance: 8
      viewDistance: 64
      levelName: level
      levelSeed:
      gameMode: survival
      defaultPermission: member
      playerIdleTimeout: 120
      # One of: DEFAULT, FLAT, LEGACY
      levelType: DEFAULT
      # Force clients to use texture packs in the current world
      texturepackRequired: false
      serverName: "KennedyCraft"
      onlineMode: true
      maxThreads: 16
      cheats: true
      serviceType: LoadBalancer

    persistence:
      dataDir:
        enabled: true
        Size: 10Gi
