apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-route53
spec:
  acme:
    privateKeySecretRef:
      name: letsencrypt-production-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
