kind: Kustomization
resources:
  - ../common
  - ceph-csi-rbd
  - longhorn

patches:
- path: patch-observability-elastic-cluster.yaml
  target:
    group: elasticsearch.k8s.elastic.co
    version: v1
    kind: Elasticsearch
    name: logs

patchesStrategicMerge:
  - patch-kube-prometheus-stack.yaml
