apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitlab
resources:
  - namespace.yaml
  - release.yaml
  - ingress-patch.yaml
  - repository.yaml
  - letsencrypt-stg-root-x1.yaml
  - letsencrypt-stg-root-x2.yaml
