apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab
spec:
  interval: 1m
  chart:
    spec:
      version: 8.7.2
      chart: gitlab
      sourceRef:
        kind: HelmRepository
        name: gitlab
      interval: 1m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  timeout: 30m
  values:
    global:
      edition: ce
      hosts:
        domain: dev.${environment}.${domain}
      ingress:
        configureCertmanager: false
        class: gitlab-nginx
        annotations:
          kubernetes.io/tls-acme: "true"
      pages:
        enabled: true
      appConfig:
        lfs:
          enabled: true
        artifacts:
          enabled: true
        uploads:
          enabled: true
        packages:
          enabled: true
        externalDiffs:
          enabled: true
        terraformState:
          enabled: true
        ciSecureFiles:
          enabled: true
        dependencyProxy:
          enabled: true
        cron_jobs:
          # Periodically clean up stale ci_runner_machines records
          ci_runners_stale_machines_cleanup_worker:
           cron: "36 * * * *"

    nginx-ingress:
      ingressClassByName: true

    certmanager:
      install: false

    gitlab:
      gitaly:
        securityContext:
          fsGroupChangePolicy: "OnRootMismatch"

      webservice:
        ingress:
          tls:
            secretName: gitlab-tls
        minReplicas: 2

      sidekiq:
        minReplicas: 2
        concurrency: 5
        hpa:
          cpu:
            targetAverageValue: 750m

      kas:
        ingress:
          tls:
            secretName: kas-tls

      gitlab-pages:
        ingress:
          tls:
            secretName: pages-star-tls

    registry:
      resources:
        requests:
          cpu: 500m
          memory: 100Mi
      hpa:
        minReplicas: 2
        cpu:
          targetAverageUtilization: 75
      ingress:
        tls:
          secretName: registry-tls

    minio:
      persistence:
        size: 256Gi
      ingress:
        tls:
          secretName: minio-tls
      securityContext:
        fsGroupChangePolicy: "OnRootMismatch"

    prometheus:
      install: false

    redis:
      securityContext:
        fsGroupChangePolicy: "OnRootMismatch"

    gitlab-runner:
      install: true
      rbac:
        clusterWideAccess: true
        create: true
      replicas: 1
      concurrent: 100
      checkInterval: 5
      logFormat: json
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      service:
        enabled: true
      sessionServer:
        enabled: false
      runners:
        config: |
          [[runners]]
            pre_get_sources_script = '''
              ##### Runner pre_get_sources_script #####
              cat /etc/resolv.conf | sed -r "s/^(options.*)/#\1/" > /tmp/resolv && cat /tmp/resolv > /etc/resolv.conf
            '''

            [runners.kubernetes]
              privileged = true
              image = "gitlab.dev.services.k9s.io:443/ci/dependency_proxy/containers/ubuntu:22.04"
              helper_image_flavor = "ubuntu"
              namespace = "ci-builds"
              namespace_overwrite_allowed = "ci-.*"

              poll_interval = 5
              poll_timeout = 3600

              # build container
              cpu_request = "1"
              cpu_limit = "4"
              memory_request = "1Gi"
              memory_limit = "6Gi"

              # service containers
              service_cpu_request = "1"
              service_cpu_limit = "4"
              service_memory_request = "1Gi"
              service_memory_limit = "6Gi"

              # helper container
              helper_cpu_request = "100m"
              helper_cpu_limit = "2"
              helper_memory_request = "500Mi"
              helper_memory_limit = "1Gi"
          
            [runners.kubernetes.pod_annotations]
              "fluentbit.io/exclude" = "true"
          
            [[runners.kubernetes.volumes.empty_dir]]
              name = "docker-certs"
              mount_path = "/certs/client"
              medium = "Memory"
              size_limit = "1G"
          
            [[runners.kubernetes.volumes.empty_dir]]
              name = "repo"
              mount_path = "/builds"
              medium = "Memory"
              size_limit = "1G"
          
            {{- if .Values.global.minio.enabled }}
            [runners.cache]
              Type = "s3"
              Path = "gitlab-runner"
              Shared = true
              [runners.cache.s3]
                ServerAddress = {{ include "gitlab-runner.cache-tpl.s3ServerAddress" . }}
                BucketName = "runner-cache"
                BucketLocation = "us-east-1"
                Insecure = false
            {{ end }}
      podAnnotations:
        gitlab.com/prometheus_scrape: "true"
        gitlab.com/prometheus_port: 9252
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - apiVersion: networking.k8s.io/v1
            kind: Ingress
            metadata:
              name: gitlab-webservice-default
              namespace: gitlab
            spec:
              ingressClassName: nginx-external-noauth
          - apiVersion: networking.k8s.io/v1
            kind: Ingress
            metadata:
              name: gitlab-gitlab-pages
              namespace: gitlab
            spec:
              ingressClassName: nginx-external-noauth
