---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: infrastructure-crds
spec:
  path: ./flux/k9s.io/infrastructure/crds
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: infrastructure-services
spec:
  path: ./flux/k9s.io/infrastructure/services/common
  dependsOn:
    - name: infrastructure-crds
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: infrastructure-config
spec:
  path: ./flux/k9s.io/infrastructure/config/common
  dependsOn:
    - name: infrastructure-services
#---
#apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
#kind: Kustomization
#metadata:
#  name: infrastructure-services-beta
#spec:
#  path: ./k9s.io/infrastructure/services/beta
#  dependsOn:
#    - name: infrastructure-services
