kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
      endpoint = ["http://registry:5000"]
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
      endpoint = ["http://proxy-docker-io:5000"]
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."k8s.gcr.io"]
      endpoint = ["http://proxy-k8s-gcr-io:5000"]
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."quay.io"]
      endpoint = ["http://proxy-quay-io:5000"]
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."gcr.io"]
      endpoint = ["http://proxy-gcr-io:5000"]
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."registry.gitlab.com"]
      endpoint = ["http://proxy-gitlab-com:5000"]
nodes:
- role: control-plane
  image: kindest/node:current
- role: worker
  image: kindest/node:current
- role: worker
  image: kindest/node:current
- role: worker
  image: kindest/node:current
