---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: not-important
spec:
  interval: 10s
  sourceRef:
    kind: Bucket
    name: minio-bucket
  prune: true
  validation: client
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: env-config-map
