apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb-controller
spec:
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: "2.5.16"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/bitnami/charts/blob/master/bitnami/metallb/values.yaml
  values:
    configInline:
      address-pools:
        - name: generic-cluster-pool
          protocol: layer2
          addresses:
            - ${metallb_pool}
