---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: not-important
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  validation: client
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: env-config-map
