apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: infrastructure-global
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/k9s.io/infrastructure/global
  prune: true
  validation: client
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: env-config-map
